name: Action Jackson
on:
  push:
    branches:
      - test
      - develop
      - master
jobs:
  autotag:
    name: Auto Tagging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: juliansangillo/tag-version@v1.5
