name: Action Jackson
on:
  push:
    branches:
      - test
      - develop
      - master
jobs:
  autotag:
    runs-on: ubuntu-latest
    name: Auto Tagging
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Version
        id: version
        uses: juliansangillo/tag-version@v1.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
